version: '3.8'

services:
  admin:
    build:
      context: ./admin
      target: development
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    volumes:
      - ./admin:/app

  patient:
    build:
      context: ./patient
      target: development
    ports:
      - "4001:4001"
    environment:
      NODE_ENV: development
    volumes:
      - ./patient:/app

  provider:
    build:
      context: ./provider
      target: development
    ports:
      - "4002:4002"
    environment:
      NODE_ENV: development
    volumes:
      - ./provider:/app
